services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_express

    ports:
      - "3000:3000"

    volumes:
      - ./backend:/app
      - /app/node_modules

    env_file:
      - ./backend/.env

    environment:
      - NODE_ENV=development

    extra_hosts:
      - "host.docker.internal:host-gateway"